# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # https://docs.vagrantup.com.

  # You can search for boxes at https://vagrantcloud.com/search.
  config.vm.box = "ubuntu/focal64"
  # config.vm.box = "geerlingguy/ubuntu2004"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.56.15"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Disable the default share of the current code directory. Doing this
  # provides improved isolation between the vagrant box and your host
  # by making sure your Vagrantfile isn't accessible to the vagrant box.
  # If you use this you may want to enable additional shared subfolders as
  # shown above.
  config.vm.synced_folder ".", "/vagrant", disabled: false

  config.vm.provider "virtualbox" do |v|
    v.name = "test-bootcamp-linux-vm"
    v.memory = 2048
    v.cpus = 1
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  end

  # require VAGRANT_EXPERIMENTAL="disks"
  # config.vm.disk :disk, size: "1GB", name: "vm-test-lvm"

  config.vm.provision "file", source: "/opt/CODE/EPAM/DevOps-Advanced/Linux7-Tasks/.src/tester", destination: "/home/vagrant/tester"
  config.vm.provision "shell", path: "vm.sh"
end
